# Generated by Django 5.0.5 on 2024-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supermarket", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("prediction_date", models.DateField()),
                ("prediction", models.FloatField()),
            ],
        ),
    ]
